version: '3.8'
services:
  app:
    build: .
    container_name: php-api
    restart: always
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: php_project
      MYSQL_USER: test
      MYSQL_PASSWORD: test@123
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
